import {
  freeRecipeGenerationsLeft,
  hasUserActiveSubscription,
} from "@/lib/freeTrial";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import SearchPage from "./components/Search";

export const metadata: Metadata = {
  title: "Search",
  description: "Search for recipes generated by Bubu AI",
};

const page = async () => {
  const hasActiveSubscription = await hasUserActiveSubscription();
  const generationsLeft = await freeRecipeGenerationsLeft();

  if (!hasActiveSubscription && generationsLeft === 0) {
    redirect("/billing");
  }
  return <SearchPage />;
};

export default page;
