import { Metadata } from "next";
import SearchPage from "./components/Search";

export const metadata: Metadata = {
  title: "Search",
  description: "Search for recipes generated by Bubu AI",
};

const page = async () => {
  return <SearchPage />;
};

export default page;
