import { Metadata } from "next";
import RecipeDetailPage from "../_components/RecipeDetailPage";

export const metadata: Metadata = {
  title: "Bubu AI - Recipe",
  description: "Recipe generated by Bubu AI",
};

const page = () => {
  return <RecipeDetailPage />;
};

export default page;
