import { Metadata } from "next";
import MenuDetails from "../_components/MenuDetails";

export const metadata: Metadata = {
  title: "Menu",
  description: "Menu generated by Bubu AI",
};

const MenuDetailsPage = () => {
  return <MenuDetails />;
};

export default MenuDetailsPage;
