import { GroceryList } from "@/components/GroceryList";
import {
  freeRecipeGenerationsLeft,
  hasUserActiveSubscription,
} from "@/lib/freeTrial";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Grocery List",
  description: "Grocery list generated by Bubu AI",
};

const GroceriesPage = async () => {
  const hasActiveSubscription = await hasUserActiveSubscription();
  const generationsLeft = await freeRecipeGenerationsLeft();

  if (!hasActiveSubscription && generationsLeft === 0) {
    redirect("/billing");
  }
  return (
    <div className="pb-8">
      <GroceryList />
    </div>
  );
};

export default GroceriesPage;
