import { GroceryList } from "@/components/GroceryList";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Grocery List",
  description: "Grocery list generated by Bubu AI",
};

const GroceriesPage = async () => {
  return (
    <div className="pb-8">
      <GroceryList />
    </div>
  );
};

export default GroceriesPage;
