import { Metadata } from "next";
import RecipeDetails from "./_components/RecipeDetails";

export const metadata: Metadata = {
  title: "Recipes",
  description: "Recipes generated by Bubu AI",
};

const RecipesPage = () => {
  return <RecipeDetails />;
};

export default RecipesPage;
