import {
  freeRecipeGenerationsLeft,
  hasUserActiveSubscription,
} from "@/lib/freeTrial";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import RecipeDetails from "./_components/RecipeDetails";

export const metadata: Metadata = {
  title: "Recipes",
  description: "Recipes generated by Bubu AI",
};

const RecipesPage = async () => {
  const hasActiveSubscription = await hasUserActiveSubscription();
  const generationsLeft = await freeRecipeGenerationsLeft();

  if (!hasActiveSubscription && generationsLeft === 0) {
    redirect("/billing");
  }

  return <RecipeDetails />;
};

export default RecipesPage;
